// Generated by jextract

package steamflat4j;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct GSClientAchievementStatus_t {
 *     uint64 m_SteamID;
 *     char m_pchAchievement[128];
 *     bool m_bUnlocked;
 * }
 * }
 */
public class GSClientAchievementStatus_t {

    GSClientAchievementStatus_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SteamFlat4j.C_LONG_LONG.withName("m_SteamID"),
        MemoryLayout.sequenceLayout(128, SteamFlat4j.C_CHAR).withName("m_pchAchievement"),
        SteamFlat4j.C_BOOL.withName("m_bUnlocked"),
        MemoryLayout.paddingLayout(7)
    ).withName("GSClientAchievementStatus_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong m_SteamID$LAYOUT = (OfLong)$LAYOUT.select(groupElement("m_SteamID"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64 m_SteamID
     * }
     */
    public static final OfLong m_SteamID$layout() {
        return m_SteamID$LAYOUT;
    }

    private static final long m_SteamID$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64 m_SteamID
     * }
     */
    public static final long m_SteamID$offset() {
        return m_SteamID$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64 m_SteamID
     * }
     */
    public static long m_SteamID(MemorySegment struct) {
        return struct.get(m_SteamID$LAYOUT, m_SteamID$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64 m_SteamID
     * }
     */
    public static void m_SteamID(MemorySegment struct, long fieldValue) {
        struct.set(m_SteamID$LAYOUT, m_SteamID$OFFSET, fieldValue);
    }

    private static final SequenceLayout m_pchAchievement$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("m_pchAchievement"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char m_pchAchievement[128]
     * }
     */
    public static final SequenceLayout m_pchAchievement$layout() {
        return m_pchAchievement$LAYOUT;
    }

    private static final long m_pchAchievement$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char m_pchAchievement[128]
     * }
     */
    public static final long m_pchAchievement$offset() {
        return m_pchAchievement$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char m_pchAchievement[128]
     * }
     */
    public static MemorySegment m_pchAchievement(MemorySegment struct) {
        return struct.asSlice(m_pchAchievement$OFFSET, m_pchAchievement$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char m_pchAchievement[128]
     * }
     */
    public static void m_pchAchievement(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, m_pchAchievement$OFFSET, m_pchAchievement$LAYOUT.byteSize());
    }

    private static long[] m_pchAchievement$DIMS = { 128 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char m_pchAchievement[128]
     * }
     */
    public static long[] m_pchAchievement$dimensions() {
        return m_pchAchievement$DIMS;
    }
    private static final VarHandle m_pchAchievement$ELEM_HANDLE = m_pchAchievement$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char m_pchAchievement[128]
     * }
     */
    public static byte m_pchAchievement(MemorySegment struct, long index0) {
        return (byte)m_pchAchievement$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char m_pchAchievement[128]
     * }
     */
    public static void m_pchAchievement(MemorySegment struct, long index0, byte fieldValue) {
        m_pchAchievement$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final OfBoolean m_bUnlocked$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("m_bUnlocked"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool m_bUnlocked
     * }
     */
    public static final OfBoolean m_bUnlocked$layout() {
        return m_bUnlocked$LAYOUT;
    }

    private static final long m_bUnlocked$OFFSET = 136;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool m_bUnlocked
     * }
     */
    public static final long m_bUnlocked$offset() {
        return m_bUnlocked$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool m_bUnlocked
     * }
     */
    public static boolean m_bUnlocked(MemorySegment struct) {
        return struct.get(m_bUnlocked$LAYOUT, m_bUnlocked$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool m_bUnlocked
     * }
     */
    public static void m_bUnlocked(MemorySegment struct, boolean fieldValue) {
        struct.set(m_bUnlocked$LAYOUT, m_bUnlocked$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

