// Generated by jextract

package steamflat4j;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct LeaderboardScoresDownloaded_t {
 *     SteamLeaderboard_t m_hSteamLeaderboard;
 *     SteamLeaderboardEntries_t m_hSteamLeaderboardEntries;
 *     int m_cEntryCount;
 * }
 * }
 */
public class LeaderboardScoresDownloaded_t {

    LeaderboardScoresDownloaded_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SteamFlat4j.C_LONG_LONG.withName("m_hSteamLeaderboard"),
        SteamFlat4j.C_LONG_LONG.withName("m_hSteamLeaderboardEntries"),
        SteamFlat4j.C_INT.withName("m_cEntryCount"),
        MemoryLayout.paddingLayout(4)
    ).withName("LeaderboardScoresDownloaded_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong m_hSteamLeaderboard$LAYOUT = (OfLong)$LAYOUT.select(groupElement("m_hSteamLeaderboard"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SteamLeaderboard_t m_hSteamLeaderboard
     * }
     */
    public static final OfLong m_hSteamLeaderboard$layout() {
        return m_hSteamLeaderboard$LAYOUT;
    }

    private static final long m_hSteamLeaderboard$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SteamLeaderboard_t m_hSteamLeaderboard
     * }
     */
    public static final long m_hSteamLeaderboard$offset() {
        return m_hSteamLeaderboard$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SteamLeaderboard_t m_hSteamLeaderboard
     * }
     */
    public static long m_hSteamLeaderboard(MemorySegment struct) {
        return struct.get(m_hSteamLeaderboard$LAYOUT, m_hSteamLeaderboard$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SteamLeaderboard_t m_hSteamLeaderboard
     * }
     */
    public static void m_hSteamLeaderboard(MemorySegment struct, long fieldValue) {
        struct.set(m_hSteamLeaderboard$LAYOUT, m_hSteamLeaderboard$OFFSET, fieldValue);
    }

    private static final OfLong m_hSteamLeaderboardEntries$LAYOUT = (OfLong)$LAYOUT.select(groupElement("m_hSteamLeaderboardEntries"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SteamLeaderboardEntries_t m_hSteamLeaderboardEntries
     * }
     */
    public static final OfLong m_hSteamLeaderboardEntries$layout() {
        return m_hSteamLeaderboardEntries$LAYOUT;
    }

    private static final long m_hSteamLeaderboardEntries$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SteamLeaderboardEntries_t m_hSteamLeaderboardEntries
     * }
     */
    public static final long m_hSteamLeaderboardEntries$offset() {
        return m_hSteamLeaderboardEntries$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SteamLeaderboardEntries_t m_hSteamLeaderboardEntries
     * }
     */
    public static long m_hSteamLeaderboardEntries(MemorySegment struct) {
        return struct.get(m_hSteamLeaderboardEntries$LAYOUT, m_hSteamLeaderboardEntries$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SteamLeaderboardEntries_t m_hSteamLeaderboardEntries
     * }
     */
    public static void m_hSteamLeaderboardEntries(MemorySegment struct, long fieldValue) {
        struct.set(m_hSteamLeaderboardEntries$LAYOUT, m_hSteamLeaderboardEntries$OFFSET, fieldValue);
    }

    private static final OfInt m_cEntryCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("m_cEntryCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int m_cEntryCount
     * }
     */
    public static final OfInt m_cEntryCount$layout() {
        return m_cEntryCount$LAYOUT;
    }

    private static final long m_cEntryCount$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int m_cEntryCount
     * }
     */
    public static final long m_cEntryCount$offset() {
        return m_cEntryCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int m_cEntryCount
     * }
     */
    public static int m_cEntryCount(MemorySegment struct) {
        return struct.get(m_cEntryCount$LAYOUT, m_cEntryCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int m_cEntryCount
     * }
     */
    public static void m_cEntryCount(MemorySegment struct, int fieldValue) {
        struct.set(m_cEntryCount$LAYOUT, m_cEntryCount$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

