// Generated by jextract

package steamflat4j;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct PersonaStateChange_t {
 *     uint64 m_ulSteamID;
 *     int m_nChangeFlags;
 * }
 * }
 */
public class PersonaStateChange_t {

    PersonaStateChange_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SteamFlat4j.C_LONG_LONG.withName("m_ulSteamID"),
        SteamFlat4j.C_INT.withName("m_nChangeFlags"),
        MemoryLayout.paddingLayout(4)
    ).withName("PersonaStateChange_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong m_ulSteamID$LAYOUT = (OfLong)$LAYOUT.select(groupElement("m_ulSteamID"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64 m_ulSteamID
     * }
     */
    public static final OfLong m_ulSteamID$layout() {
        return m_ulSteamID$LAYOUT;
    }

    private static final long m_ulSteamID$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64 m_ulSteamID
     * }
     */
    public static final long m_ulSteamID$offset() {
        return m_ulSteamID$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64 m_ulSteamID
     * }
     */
    public static long m_ulSteamID(MemorySegment struct) {
        return struct.get(m_ulSteamID$LAYOUT, m_ulSteamID$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64 m_ulSteamID
     * }
     */
    public static void m_ulSteamID(MemorySegment struct, long fieldValue) {
        struct.set(m_ulSteamID$LAYOUT, m_ulSteamID$OFFSET, fieldValue);
    }

    private static final OfInt m_nChangeFlags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("m_nChangeFlags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int m_nChangeFlags
     * }
     */
    public static final OfInt m_nChangeFlags$layout() {
        return m_nChangeFlags$LAYOUT;
    }

    private static final long m_nChangeFlags$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int m_nChangeFlags
     * }
     */
    public static final long m_nChangeFlags$offset() {
        return m_nChangeFlags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int m_nChangeFlags
     * }
     */
    public static int m_nChangeFlags(MemorySegment struct) {
        return struct.get(m_nChangeFlags$LAYOUT, m_nChangeFlags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int m_nChangeFlags
     * }
     */
    public static void m_nChangeFlags(MemorySegment struct, int fieldValue) {
        struct.set(m_nChangeFlags$LAYOUT, m_nChangeFlags$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

