// Generated by jextract

package steamflat4j;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SteamParamStringArray_t {
 *     const char **m_ppStrings;
 *     int32 m_nNumStrings;
 * }
 * }
 */
public class SteamParamStringArray_t {

    SteamParamStringArray_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SteamFlat4j.C_POINTER.withName("m_ppStrings"),
        SteamFlat4j.C_INT.withName("m_nNumStrings"),
        MemoryLayout.paddingLayout(4)
    ).withName("SteamParamStringArray_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout m_ppStrings$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("m_ppStrings"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char **m_ppStrings
     * }
     */
    public static final AddressLayout m_ppStrings$layout() {
        return m_ppStrings$LAYOUT;
    }

    private static final long m_ppStrings$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char **m_ppStrings
     * }
     */
    public static final long m_ppStrings$offset() {
        return m_ppStrings$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char **m_ppStrings
     * }
     */
    public static MemorySegment m_ppStrings(MemorySegment struct) {
        return struct.get(m_ppStrings$LAYOUT, m_ppStrings$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char **m_ppStrings
     * }
     */
    public static void m_ppStrings(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(m_ppStrings$LAYOUT, m_ppStrings$OFFSET, fieldValue);
    }

    private static final OfInt m_nNumStrings$LAYOUT = (OfInt)$LAYOUT.select(groupElement("m_nNumStrings"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32 m_nNumStrings
     * }
     */
    public static final OfInt m_nNumStrings$layout() {
        return m_nNumStrings$LAYOUT;
    }

    private static final long m_nNumStrings$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32 m_nNumStrings
     * }
     */
    public static final long m_nNumStrings$offset() {
        return m_nNumStrings$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32 m_nNumStrings
     * }
     */
    public static int m_nNumStrings(MemorySegment struct) {
        return struct.get(m_nNumStrings$LAYOUT, m_nNumStrings$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32 m_nNumStrings
     * }
     */
    public static void m_nNumStrings(MemorySegment struct, int fieldValue) {
        struct.set(m_nNumStrings$LAYOUT, m_nNumStrings$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

