// Generated by jextract

package steamflat4j;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct GameConnectedClanChatMsg_t {
 *     CSteamID m_steamIDClanChat;
 *     CSteamID m_steamIDUser;
 *     int m_iMessageID;
 * }
 * }
 */
public class GameConnectedClanChatMsg_t {

    GameConnectedClanChatMsg_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SteamFlat.C_LONG_LONG.withName("m_steamIDClanChat"),
        SteamFlat.C_LONG_LONG.withName("m_steamIDUser"),
        SteamFlat.C_INT.withName("m_iMessageID"),
        MemoryLayout.paddingLayout(4)
    ).withName("GameConnectedClanChatMsg_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong m_steamIDClanChat$LAYOUT = (OfLong)$LAYOUT.select(groupElement("m_steamIDClanChat"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * CSteamID m_steamIDClanChat
     * }
     */
    public static final OfLong m_steamIDClanChat$layout() {
        return m_steamIDClanChat$LAYOUT;
    }

    private static final long m_steamIDClanChat$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * CSteamID m_steamIDClanChat
     * }
     */
    public static final long m_steamIDClanChat$offset() {
        return m_steamIDClanChat$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * CSteamID m_steamIDClanChat
     * }
     */
    public static long m_steamIDClanChat(MemorySegment struct) {
        return struct.get(m_steamIDClanChat$LAYOUT, m_steamIDClanChat$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * CSteamID m_steamIDClanChat
     * }
     */
    public static void m_steamIDClanChat(MemorySegment struct, long fieldValue) {
        struct.set(m_steamIDClanChat$LAYOUT, m_steamIDClanChat$OFFSET, fieldValue);
    }

    private static final OfLong m_steamIDUser$LAYOUT = (OfLong)$LAYOUT.select(groupElement("m_steamIDUser"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * CSteamID m_steamIDUser
     * }
     */
    public static final OfLong m_steamIDUser$layout() {
        return m_steamIDUser$LAYOUT;
    }

    private static final long m_steamIDUser$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * CSteamID m_steamIDUser
     * }
     */
    public static final long m_steamIDUser$offset() {
        return m_steamIDUser$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * CSteamID m_steamIDUser
     * }
     */
    public static long m_steamIDUser(MemorySegment struct) {
        return struct.get(m_steamIDUser$LAYOUT, m_steamIDUser$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * CSteamID m_steamIDUser
     * }
     */
    public static void m_steamIDUser(MemorySegment struct, long fieldValue) {
        struct.set(m_steamIDUser$LAYOUT, m_steamIDUser$OFFSET, fieldValue);
    }

    private static final OfInt m_iMessageID$LAYOUT = (OfInt)$LAYOUT.select(groupElement("m_iMessageID"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int m_iMessageID
     * }
     */
    public static final OfInt m_iMessageID$layout() {
        return m_iMessageID$LAYOUT;
    }

    private static final long m_iMessageID$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int m_iMessageID
     * }
     */
    public static final long m_iMessageID$offset() {
        return m_iMessageID$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int m_iMessageID
     * }
     */
    public static int m_iMessageID(MemorySegment struct) {
        return struct.get(m_iMessageID$LAYOUT, m_iMessageID$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int m_iMessageID
     * }
     */
    public static void m_iMessageID(MemorySegment struct, int fieldValue) {
        struct.set(m_iMessageID$LAYOUT, m_iMessageID$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

