// Generated by jextract

package steamflat4j;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ItemInstalled_t {
 *     AppId_t m_unAppID;
 *     PublishedFileId_t m_nPublishedFileId;
 * }
 * }
 */
public class ItemInstalled_t {

    ItemInstalled_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SteamFlat.C_INT.withName("m_unAppID"),
        MemoryLayout.paddingLayout(4),
        SteamFlat.C_LONG_LONG.withName("m_nPublishedFileId")
    ).withName("ItemInstalled_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt m_unAppID$LAYOUT = (OfInt)$LAYOUT.select(groupElement("m_unAppID"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AppId_t m_unAppID
     * }
     */
    public static final OfInt m_unAppID$layout() {
        return m_unAppID$LAYOUT;
    }

    private static final long m_unAppID$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AppId_t m_unAppID
     * }
     */
    public static final long m_unAppID$offset() {
        return m_unAppID$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AppId_t m_unAppID
     * }
     */
    public static int m_unAppID(MemorySegment struct) {
        return struct.get(m_unAppID$LAYOUT, m_unAppID$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AppId_t m_unAppID
     * }
     */
    public static void m_unAppID(MemorySegment struct, int fieldValue) {
        struct.set(m_unAppID$LAYOUT, m_unAppID$OFFSET, fieldValue);
    }

    private static final OfLong m_nPublishedFileId$LAYOUT = (OfLong)$LAYOUT.select(groupElement("m_nPublishedFileId"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PublishedFileId_t m_nPublishedFileId
     * }
     */
    public static final OfLong m_nPublishedFileId$layout() {
        return m_nPublishedFileId$LAYOUT;
    }

    private static final long m_nPublishedFileId$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PublishedFileId_t m_nPublishedFileId
     * }
     */
    public static final long m_nPublishedFileId$offset() {
        return m_nPublishedFileId$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PublishedFileId_t m_nPublishedFileId
     * }
     */
    public static long m_nPublishedFileId(MemorySegment struct) {
        return struct.get(m_nPublishedFileId$LAYOUT, m_nPublishedFileId$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PublishedFileId_t m_nPublishedFileId
     * }
     */
    public static void m_nPublishedFileId(MemorySegment struct, long fieldValue) {
        struct.set(m_nPublishedFileId$LAYOUT, m_nPublishedFileId$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

