// Generated by jextract

package steamflat4j;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct LobbyInvite_t {
 *     uint64 m_ulSteamIDUser;
 *     uint64 m_ulSteamIDLobby;
 *     uint64 m_ulGameID;
 * }
 * }
 */
public class LobbyInvite_t {

    LobbyInvite_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SteamFlat.C_LONG_LONG.withName("m_ulSteamIDUser"),
        SteamFlat.C_LONG_LONG.withName("m_ulSteamIDLobby"),
        SteamFlat.C_LONG_LONG.withName("m_ulGameID")
    ).withName("LobbyInvite_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong m_ulSteamIDUser$LAYOUT = (OfLong)$LAYOUT.select(groupElement("m_ulSteamIDUser"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64 m_ulSteamIDUser
     * }
     */
    public static final OfLong m_ulSteamIDUser$layout() {
        return m_ulSteamIDUser$LAYOUT;
    }

    private static final long m_ulSteamIDUser$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64 m_ulSteamIDUser
     * }
     */
    public static final long m_ulSteamIDUser$offset() {
        return m_ulSteamIDUser$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64 m_ulSteamIDUser
     * }
     */
    public static long m_ulSteamIDUser(MemorySegment struct) {
        return struct.get(m_ulSteamIDUser$LAYOUT, m_ulSteamIDUser$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64 m_ulSteamIDUser
     * }
     */
    public static void m_ulSteamIDUser(MemorySegment struct, long fieldValue) {
        struct.set(m_ulSteamIDUser$LAYOUT, m_ulSteamIDUser$OFFSET, fieldValue);
    }

    private static final OfLong m_ulSteamIDLobby$LAYOUT = (OfLong)$LAYOUT.select(groupElement("m_ulSteamIDLobby"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64 m_ulSteamIDLobby
     * }
     */
    public static final OfLong m_ulSteamIDLobby$layout() {
        return m_ulSteamIDLobby$LAYOUT;
    }

    private static final long m_ulSteamIDLobby$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64 m_ulSteamIDLobby
     * }
     */
    public static final long m_ulSteamIDLobby$offset() {
        return m_ulSteamIDLobby$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64 m_ulSteamIDLobby
     * }
     */
    public static long m_ulSteamIDLobby(MemorySegment struct) {
        return struct.get(m_ulSteamIDLobby$LAYOUT, m_ulSteamIDLobby$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64 m_ulSteamIDLobby
     * }
     */
    public static void m_ulSteamIDLobby(MemorySegment struct, long fieldValue) {
        struct.set(m_ulSteamIDLobby$LAYOUT, m_ulSteamIDLobby$OFFSET, fieldValue);
    }

    private static final OfLong m_ulGameID$LAYOUT = (OfLong)$LAYOUT.select(groupElement("m_ulGameID"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64 m_ulGameID
     * }
     */
    public static final OfLong m_ulGameID$layout() {
        return m_ulGameID$LAYOUT;
    }

    private static final long m_ulGameID$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64 m_ulGameID
     * }
     */
    public static final long m_ulGameID$offset() {
        return m_ulGameID$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64 m_ulGameID
     * }
     */
    public static long m_ulGameID(MemorySegment struct) {
        return struct.get(m_ulGameID$LAYOUT, m_ulGameID$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64 m_ulGameID
     * }
     */
    public static void m_ulGameID(MemorySegment struct, long fieldValue) {
        struct.set(m_ulGameID$LAYOUT, m_ulGameID$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

