// Generated by jextract

package steamflat4j;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SteamNetworkingFakeIPResult_t {
 *     EResult m_eResult;
 *     SteamNetworkingIdentity m_identity;
 *     uint32 m_unIP;
 *     uint16 m_unPorts[8];
 * }
 * }
 */
public class SteamNetworkingFakeIPResult_t {

    SteamNetworkingFakeIPResult_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SteamFlat.C_INT.withName("m_eResult"),
        SteamNetworkingIdentity.layout().withName("m_identity"),
        SteamFlat.C_INT.withName("m_unIP"),
        MemoryLayout.sequenceLayout(8, SteamFlat.C_SHORT).withName("m_unPorts")
    ).withName("SteamNetworkingFakeIPResult_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt m_eResult$LAYOUT = (OfInt)$LAYOUT.select(groupElement("m_eResult"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * EResult m_eResult
     * }
     */
    public static final OfInt m_eResult$layout() {
        return m_eResult$LAYOUT;
    }

    private static final long m_eResult$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * EResult m_eResult
     * }
     */
    public static final long m_eResult$offset() {
        return m_eResult$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * EResult m_eResult
     * }
     */
    public static int m_eResult(MemorySegment struct) {
        return struct.get(m_eResult$LAYOUT, m_eResult$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * EResult m_eResult
     * }
     */
    public static void m_eResult(MemorySegment struct, int fieldValue) {
        struct.set(m_eResult$LAYOUT, m_eResult$OFFSET, fieldValue);
    }

    private static final GroupLayout m_identity$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("m_identity"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SteamNetworkingIdentity m_identity
     * }
     */
    public static final GroupLayout m_identity$layout() {
        return m_identity$LAYOUT;
    }

    private static final long m_identity$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SteamNetworkingIdentity m_identity
     * }
     */
    public static final long m_identity$offset() {
        return m_identity$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SteamNetworkingIdentity m_identity
     * }
     */
    public static MemorySegment m_identity(MemorySegment struct) {
        return struct.asSlice(m_identity$OFFSET, m_identity$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SteamNetworkingIdentity m_identity
     * }
     */
    public static void m_identity(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, m_identity$OFFSET, m_identity$LAYOUT.byteSize());
    }

    private static final OfInt m_unIP$LAYOUT = (OfInt)$LAYOUT.select(groupElement("m_unIP"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32 m_unIP
     * }
     */
    public static final OfInt m_unIP$layout() {
        return m_unIP$LAYOUT;
    }

    private static final long m_unIP$OFFSET = 140;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32 m_unIP
     * }
     */
    public static final long m_unIP$offset() {
        return m_unIP$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32 m_unIP
     * }
     */
    public static int m_unIP(MemorySegment struct) {
        return struct.get(m_unIP$LAYOUT, m_unIP$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32 m_unIP
     * }
     */
    public static void m_unIP(MemorySegment struct, int fieldValue) {
        struct.set(m_unIP$LAYOUT, m_unIP$OFFSET, fieldValue);
    }

    private static final SequenceLayout m_unPorts$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("m_unPorts"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16 m_unPorts[8]
     * }
     */
    public static final SequenceLayout m_unPorts$layout() {
        return m_unPorts$LAYOUT;
    }

    private static final long m_unPorts$OFFSET = 144;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16 m_unPorts[8]
     * }
     */
    public static final long m_unPorts$offset() {
        return m_unPorts$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16 m_unPorts[8]
     * }
     */
    public static MemorySegment m_unPorts(MemorySegment struct) {
        return struct.asSlice(m_unPorts$OFFSET, m_unPorts$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16 m_unPorts[8]
     * }
     */
    public static void m_unPorts(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, m_unPorts$OFFSET, m_unPorts$LAYOUT.byteSize());
    }

    private static long[] m_unPorts$DIMS = { 8 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint16 m_unPorts[8]
     * }
     */
    public static long[] m_unPorts$dimensions() {
        return m_unPorts$DIMS;
    }
    private static final VarHandle m_unPorts$ELEM_HANDLE = m_unPorts$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint16 m_unPorts[8]
     * }
     */
    public static short m_unPorts(MemorySegment struct, long index0) {
        return (short)m_unPorts$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint16 m_unPorts[8]
     * }
     */
    public static void m_unPorts(MemorySegment struct, long index0, short fieldValue) {
        m_unPorts$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

