// Generated by jextract

package steamflat4j;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SteamAPICallCompleted_t {
 *     SteamAPICall_t m_hAsyncCall;
 *     int m_iCallback;
 *     uint32 m_cubParam;
 * }
 * }
 */
public class SteamAPICallCompleted_t {

    SteamAPICallCompleted_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SteamFlat.C_LONG_LONG.withName("m_hAsyncCall"),
        SteamFlat.C_INT.withName("m_iCallback"),
        SteamFlat.C_INT.withName("m_cubParam")
    ).withName("SteamAPICallCompleted_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong m_hAsyncCall$LAYOUT = (OfLong)$LAYOUT.select(groupElement("m_hAsyncCall"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SteamAPICall_t m_hAsyncCall
     * }
     */
    public static final OfLong m_hAsyncCall$layout() {
        return m_hAsyncCall$LAYOUT;
    }

    private static final long m_hAsyncCall$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SteamAPICall_t m_hAsyncCall
     * }
     */
    public static final long m_hAsyncCall$offset() {
        return m_hAsyncCall$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SteamAPICall_t m_hAsyncCall
     * }
     */
    public static long m_hAsyncCall(MemorySegment struct) {
        return struct.get(m_hAsyncCall$LAYOUT, m_hAsyncCall$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SteamAPICall_t m_hAsyncCall
     * }
     */
    public static void m_hAsyncCall(MemorySegment struct, long fieldValue) {
        struct.set(m_hAsyncCall$LAYOUT, m_hAsyncCall$OFFSET, fieldValue);
    }

    private static final OfInt m_iCallback$LAYOUT = (OfInt)$LAYOUT.select(groupElement("m_iCallback"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int m_iCallback
     * }
     */
    public static final OfInt m_iCallback$layout() {
        return m_iCallback$LAYOUT;
    }

    private static final long m_iCallback$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int m_iCallback
     * }
     */
    public static final long m_iCallback$offset() {
        return m_iCallback$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int m_iCallback
     * }
     */
    public static int m_iCallback(MemorySegment struct) {
        return struct.get(m_iCallback$LAYOUT, m_iCallback$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int m_iCallback
     * }
     */
    public static void m_iCallback(MemorySegment struct, int fieldValue) {
        struct.set(m_iCallback$LAYOUT, m_iCallback$OFFSET, fieldValue);
    }

    private static final OfInt m_cubParam$LAYOUT = (OfInt)$LAYOUT.select(groupElement("m_cubParam"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32 m_cubParam
     * }
     */
    public static final OfInt m_cubParam$layout() {
        return m_cubParam$LAYOUT;
    }

    private static final long m_cubParam$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32 m_cubParam
     * }
     */
    public static final long m_cubParam$offset() {
        return m_cubParam$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32 m_cubParam
     * }
     */
    public static int m_cubParam(MemorySegment struct) {
        return struct.get(m_cubParam$LAYOUT, m_cubParam$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32 m_cubParam
     * }
     */
    public static void m_cubParam(MemorySegment struct, int fieldValue) {
        struct.set(m_cubParam$LAYOUT, m_cubParam$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

